### PR TITLE
- 'theme' => 'vr',

### PR DESCRIPTION
**Pull request by 160damage**
- 'theme' => $ctx->mod('theme'),

modified:   common.blocks/widget/__preloader/widget__preloader.bh.php
modified:   common.blocks/widget/_type/widget_type_broadcasts.bh.php
modified:   common.blocks/widget/_type/widget_type_comments.bh.php
modified:   common.blocks/widget/_type/widget_type_posts.bh.php

### CODE REVIEW

**Comment by kompolom** [comment]
@160damage ты тесты не прогонял, проходят?

**Comment by 160damage** [comment]
не прогонял

**Comment by kompolom** [comment]
@160damage попробуй `npm run unit`

**Comment by 160damage** [comment]
как этот скрипт работает?
и что для него нужно установить,ибо мне выдает вот
 Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "lint"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ap-components@1.0.0 lint: `jshint-groups && jscs .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ap-components@1.0.0 lint script 'jshint-groups && jscs .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ap-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jshint-groups && jscs .
npm ERR! You can get their info via:
npm ERR!     npm owner ls ap-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\new\1\ap-components\npm-debug.log

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "unit"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! ap-components@1.0.0 unit: `npm run lint && npm run tmpls && npm run specs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ap-components@1.0.0 unit script 'npm run lint && npm run tmpls && npm run specs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ap-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run tmpls && npm run specs
npm ERR! You can get their info via:
npm ERR!     npm owner ls ap-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\new\1\ap-components\npm-debug.log

я еще на ноуте сижу своем,сейчас ставлю убунту на рабочий комп

**Comment by 160damage** [comment]
и что собственно мне нужно будет сейчас установить на рабочий комп
ноду 4 версии
какие модули и прочее?

**Comment by kompolom** [comment]
@160damage это весь вывод? или вначале идут ошибки в тестах?

**Comment by 160damage** [comment]
> D:\new\1\ap-components [master]> npm run unit
> 
> > ap-components@1.0.0 unit D:\new\1\ap-components
> > npm run lint && npm run tmpls && npm run specs
> > 
> > ap-components@1.0.0 lint D:\new\1\ap-components
> > jshint-groups && jscs .
> 
> module.js:328
>     throw err;
>     ^
> 
> Error: Cannot find module 'jshint'
>     at Function.Module._resolveFilename (module.js:326:15)
>     at Function.Module._load (module.js:277:25)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\Egor\AppData\Roaming\npm\node_modules\jshint-groups\bin\jshint-groups:8:14)
>     at Module._compile (module.js:398:26)
>     at Object.Module._extensions..js (module.js:405:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:430:10)
> 
> npm ERR! Windows_NT 10.0.10240
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "lint"
> npm ERR! node v5.3.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> npm ERR! ap-components@1.0.0 lint: `jshint-groups && jscs .`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ap-components@1.0.0 lint script 'jshint-groups && jscs .'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ap-components package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     jshint-groups && jscs .
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls ap-components
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\new\1\ap-components\npm-debug.log
> 
> npm ERR! Windows_NT 10.0.10240
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "unit"
> npm ERR! node v5.3.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> npm ERR! ap-components@1.0.0 unit: `npm run lint && npm run tmpls && npm run specs`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ap-components@1.0.0 unit script 'npm run lint && npm run tmpls && npm run specs'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ap-components package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run lint && npm run tmpls && npm run specs
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls ap-components
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\new\1\ap-components\npm-debug.log

**Comment by kompolom** [comment]
@160damage 

```
Error: Cannot find module 'jshint'
```

намекает что не установлен jshint. Его можно установить глобально. `npm i jshint -g`

**Comment by 160damage** [comment]
установил еще jscs

D:\new\1\ap-components [master]> npm run unit

> ap-components@1.0.0 unit D:\new\1\ap-components
> npm run lint && npm run tmpls && npm run specs
> 
> ap-components@1.0.0 lint D:\new\1\ap-components
> jshint-groups && jscs .

lint group "browserjs"
lint group "specjs"
lint group "bemhtml"
lint group "bhjs"
`plugin` should be a function

**Pull request closed without merging**
